_format_version: "2.1"

services:

- name: product-service
  url: http://product:8002
  routes:
  - name: product-service-routes
    paths:
    - /

# plugins section
# plugins:
# - name: correlation-id
#   config: 
#     header_name: Request-ID
#     generator: tracker
#     echo_downstream: false
# - name: prometheus
#   config:
#     status_code_metrics: true
#     latency_metrics: true
#     bandwidth_metrics: true
#     upstream_health_metrics: true



